services:
  postgres:
    image: postgres:17.4
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-inferno-games}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-inferno-games}
      POSTGRES_DB: ${POSTGRES_DB:-inferno-games}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - inferno-games-network

  redis:
    image: redis:latest
    container_name: my_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=inferno-games
    command: redis-server --appendonly yes
    networks:
      - inferno-games-network

volumes:
  postgres-data:
  redis_data:

networks:
  inferno-games-network:
    driver: bridge
