app:
  version: 0.1.2

server:
  servlet:
    contextPath: /${URL_PREFIX}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  application:
    name: inferno-games-rest
  profiles:
    active: local